In [ ]:
#print
print("This line will be printed.")

In [ ]:
# indent
x = 1
if x == 1:
    print("x is 1.")

In [5]:
#variables and types
myint = 7
print(myint)

myfloat = 7.0
print(myfloat)
myfloat = float(7)
print(myfloat)

mystring = 'hello'
print(mystring)

mystring = "Don't worry about apostrophes"
print(mystring)

a, b = 3, 4
print(a,b)

one = "1"
two = "2"
hello = "hello"
print(one + two + hello)



mystring = "hello"
myfloat = 10.0
myint = 20
if mystring == "hello":
    print("String: %s" % mystring)
if isinstance(myfloat, float) and myfloat == 10.0:
    print("Float: %f" % myfloat)
if isinstance(myint, int) and myint == 20:
    print("Integer: %d" % myint)

7
7.0
7.0
hello
Don't worry about apostrophes
(3, 4)
12hello
String: hello
Float: 10.000000
Integer: 20

In [12]:
#lists
mylist = []
mylist.append(1)
mylist.append(2)
mylist.append(3)
print(mylist[0])
print(mylist[1])
print(mylist[2]) 
print "----"
for x in mylist:
    print(x)
    
    
#mylist = [1,2,3]
#print(mylist[10])
#out of range


numbers = [1,2]
strings = ["bob","jane"]
names = ["John", "Eric", "Jessica"]
second_name = names[1]
print(numbers)
print(strings)
print("The second name on the names list is %s" % second_name)

1
2
3
----
1
2
3
[1, 2]
['bob', 'jane']
The second name on the names list is Eric

In [17]:
#basic operators

remainder = 11 % 3
print(remainder)

squared = 7 ** 2
cubed = 2 ** 3

helloworld = "hello" + " " + "world"
print(helloworld)

even_numbers = [2,4,6,8]
odd_numbers = [1,3,5,7]
all_numbers = odd_numbers + even_numbers
print(all_numbers)

print([1,2,3] * 3)



x = object()
y = object()
x_list = [x] * 10
y_list = [y] * 10
big_list = x_list + y_list

print("x_list contains %d objects" % len(x_list))
print("y_list contains %d objects" % len(y_list))
print("big_list contains %d objects" % len(big_list))

if x_list.count(x) == 10 and y_list.count(y) == 10:
    print("Almost there...")
if big_list.count(x) == 10 and big_list.count(y) == 10:
    print("Great!")

2
hello world
[1, 3, 5, 7, 2, 4, 6, 8]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
x_list contains 10 objects
y_list contains 10 objects
big_list contains 20 objects
Almost there...
Great!
[<object object at 0x103234a60>, <object object at 0x103234a60>, <object object at 0x103234a60>, <object object at 0x103234a60>, <object object at 0x103234a60>, <object object at 0x103234a60>, <object object at 0x103234a60>, <object object at 0x103234a60>, <object object at 0x103234a60>, <object object at 0x103234a60>]

In [23]:
#string formatting
name = "John"
print("Hello, %s!" % name)

age = 23
print("%s is %d years old." % (name, age))

mylist = [1,2,3]
print("A list: %s" % mylist)

data = ("John", "Doe", 53.44)
format_string = "Hello %s %s. Your current balance is $%s."

print(format_string % data)

#string operators
astring = "Hello world!"
astring2 = 'Hello world!'


print(astring.index("o"))
print(astring.count("l"))
print(astring[3:7])
print(astring[3:7:2])
print(astring[3:7])
print(astring[3:7:1])
print(astring[::-1])
print(astring.upper())
print(astring.lower())
print(astring.startswith("Hello"))
print(astring.endswith("asdfasdfasdf"))
afewwords = astring.split(" ")
print(afewwords)


s = "Strings are awesome!"
print("Length of s = %d" % len(s))
print("The first occurrence of the letter a = %d" % s.index("a"))
print("a occurs %d times" % s.count("a"))
print("The first five characters are '%s'" % s[:5]) # Start to 5
print("The next five characters are '%s'" % s[5:10]) # 5 to 10
print("The thirteenth character is '%s'" % s[12]) # Just number 12
print("The characters with odd index are '%s'" %s[1::2]) #(0-based indexing)
print("The last five characters are '%s'" % s[-5:]) # 5th-from-last to end
print("String in uppercase: %s" % s.upper())
print("String in lowercase: %s" % s.lower())
if s.startswith("Str"):
    print("String starts with 'Str'. Good!")
if s.endswith("ome!"):
    print("String ends with 'ome!'. Good!")
print("Split the words of the string: %s" % s.split(" "))

Hello, John!
John is 23 years old.
A list: [1, 2, 3]
Hello John Doe. Your current balance is $53.44.
4
3
lo w
l
lo w
lo w
!dlrow olleH
HELLO WORLD!
hello world!
True
False
['Hello', 'world!']
Length of s = 20
The first occurrence of the letter a = 8
a occurs 2 times
The first five characters are 'Strin'
The next five characters are 'gs ar'
The thirteenth character is 'a'
The characters with odd index are 'tig r wsm!'
The last five characters are 'some!'
String in uppercase: STRINGS ARE AWESOME!
String in lowercase: strings are awesome!
String starts with 'Str'. Good!
String ends with 'ome!'. Good!
Split the words of the string: ['Strings', 'are', 'awesome!']

In [25]:
#conditions

x = 2
print(x == 2) 
print(x == 3)
print(x < 3)

name = "John"
age = 23
if name == "John" and age == 23:
    print("Your name is John, and you are also 23 years old.")
    
if name == "John" or name == "Rick":
    print("Your name is either John or Rick.")
    
if name in ["John", "Rick"]:
    print("Your name is either John or Rick.")
    
x = 2
if x == 2:
    print("x equals two!")
else:
    print("x does not equal to two.")
    
x = [1,2,3]
y = [1,2,3]
print(x == y)
print(x is y)

print(not False) 
print((not False) == (False)) 

number = 16
second_number = 0
first_array = [1,2,3]
second_array = [1,2]

if number > 15:
    print("1")

if first_array:
    print("2")

if len(second_array) == 2:
    print("3")

if len(first_array) + len(second_array) == 5:
    print("4")

if first_array and first_array[0] == 1:
    print("5")

if not second_number:
    print("6")

True
False
True
Your name is John, and you are also 23 years old.
Your name is either John or Rick.
Your name is either John or Rick.
x equals two!
True
False
True
False
1
2
3
4
5
6

In [27]:
#loops
for x in range(5):
    print(x)

for x in range(3, 6):
    print(x)

for x in range(3, 8, 2):
    print(x)
    
    
count = 0
while count < 5:
    print(count)
    count += 1 
    
count = 0
while True:
    print(count)
    count += 1
    if count >= 5:
        break

for x in range(10):
    if x % 2 == 0:
        continue
    print(x)
    
count=0
while(count<5):
    print(count)
    count +=1
else:
    print("count value reached %d" %(count))


for i in range(1, 10):
    if(i%5==0):
        break
    print(i)
else:
    print("this is not printed because for loop is terminated because of break but not due to fail in condition")
    
    
numbers = [
    951, 402, 984, 651, 360, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544,
    615, 83, 165, 141, 501, 263, 617, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941,
    386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345,
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
    815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
    958, 609, 842, 451, 688, 753, 854, 685, 93, 857, 440, 380, 126, 721, 328, 753, 470,
    743, 527
]

for number in numbers:
    if number == 237:
        break

    if number % 2 == 1:
        continue

    print(number)

0
1
2
3
4
3
4
5
3
5
7
0
1
2
3
4
0
1
2
3
4
1
3
5
7
9
0
1
2
3
4
count value reached 5
1
2
3
4
402
984
360
408
980
544
390
984
592
236
942
386
462
418
344
236
566
978
328
162
758
918

In [30]:
#functions
def my_function():
    print("Hello From My Function!")
    
def my_function_with_args(username, greeting):
    print("Hello, %s , From My Function!, I wish you %s"%(username, greeting))
    
def sum_two_numbers(a, b):
    return a + b


my_function()
my_function_with_args("John Doe", "a great year!")
x = sum_two_numbers(1,2)


def list_benefits():
    return "More organized code", "More readable code", "Easier code reuse", "Allowing programmers to share and connect code together"

def build_sentence(benefit):
    return "%s is a benefit of functions!" % benefit

def name_the_benefits_of_functions():
    list_of_benefits = list_benefits()
    for benefit in list_of_benefits:
        print(build_sentence(benefit))

name_the_benefits_of_functions()

Hello From My Function!
Hello, John Doe , From My Function!, I wish you a great year!
More organized code is a benefit of functions!
More readable code is a benefit of functions!
Easier code reuse is a benefit of functions!
Allowing programmers to share and connect code together is a benefit of functions!

In [35]:
#classes and objects
class MyClass:
    variable = "blah"

    def function(self):
        print("This is a message inside the class.")
        
myobjectx = MyClass()
print myobjectx.variable



myobjectx = MyClass()
myobjecty = MyClass()

myobjecty.variable = "yackity"

print(myobjectx.variable)
print(myobjecty.variable)

myobjectx.function()


class Vehicle:
    name = ""
    kind = "car"
    color = ""
    value = 100.00
    def description(self):
        desc_str = "%s is a %s %s worth $%.2f." % (self.name, self.color, self.kind, self.value)
        return desc_str

car1 = Vehicle()
car1.name = "Fer"
car1.color = "red"
car1.kind = "convertible"
car1.value = 60000.00

car2 = Vehicle()
car2.name = "Jump"
car2.color = "blue"
car2.kind = "van"
car2.value = 10000.00

print(car1.description())
print(car2.description())

blah
blah
yackity
This is a message inside the class.
Fer is a red convertible worth $60000.00.
Jump is a blue van worth $10000.00.

In [38]:
#dictionaries, key, values
phonebook = {}
phonebook["John"] = 938477566
phonebook["Jack"] = 938377264
phonebook["Jill"] = 947662781
print(phonebook)

phonebook = {
    "John" : 938477566,
    "Jack" : 938377264,
    "Jill" : 947662781
}
print(phonebook)

for name, number in phonebook.items():
    print("Phone number of %s is %d" % (name, number))
    
del phonebook["John"]
print(phonebook)

phonebook = {
   "John" : 938477566,
   "Jack" : 938377264,
   "Jill" : 947662781
}
phonebook.pop("John")
print(phonebook)




phonebook = {
    "John" : 938477566,
    "Jack" : 938377264,
    "Jill" : 947662781
}

phonebook["Jake"] = 938273443
del phonebook["Jill"]

if "Jake" in phonebook:
    print("Jake is listed in the phonebook.")
if "Jill" not in phonebook:
    print("Jill is not listed in the phonebook.")

{'Jill': 947662781, 'John': 938477566, 'Jack': 938377264}
{'Jill': 947662781, 'John': 938477566, 'Jack': 938377264}
Phone number of Jill is 947662781
Phone number of John is 938477566
Phone number of Jack is 938377264
{'Jill': 947662781, 'Jack': 938377264}
{'Jill': 947662781, 'Jack': 938377264}

In [41]:
#modules, packages
#Modules in Python are simply Python files with the .py extension, 
#which implement a set of functions. Modules are imported from other modules using the import command.

import re

find_members = []
for member in dir(re):
    if "find" in member:
        find_members.append(member)

print(sorted(find_members))

['findall', 'finditer']

In [59]:
#Numpy, Panda Arrays
#Numpy arrays are great alternatives to Python Lists. 
#Some of the key advantages of Numpy arrays are that they are fast, easy to work with, 
#and give users the opportunity to perform calculations across entire arrays.


height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]
import numpy as np

np_height = np.array(height)
np_weight = np.array(weight)

bmi = np_weight / np_height ** 2
print(bmi)

bmi[bmi > 25]
print bmi


weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

np_weight_kg = np.array(weight_kg)
np_weight_lbs = np_weight_kg * 2.2
print(np_weight_lbs)

#Dataframe
dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
       "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
brics = pd.DataFrame(dict)
print(brics)


brics.index = ["BR", "RU", "IN", "CH", "SA"]
print(brics)


TimeSerie = pd.read_csv('Stockprice.csv')
print(TimeSerie)
print(TimeSerie['Date'])
print(TimeSerie[['Open']])
print(TimeSerie[['Open', 'Close']])
print(TimeSerie[0:4])
print(TimeSerie[4:6])

[ 23.34925219  27.88755755  28.75558507  25.48723993  23.87257618
  25.84368152]
[ 23.34925219  27.88755755  28.75558507  25.48723993  23.87257618
  25.84368152]
[ 179.63   214.544  209.55   204.556  189.596  194.59 ]
     area    capital       country  population
0   8.516   Brasilia        Brazil      200.40
1  17.100     Moscow        Russia      143.50
2   3.286  New Dehli         India     1252.00
3   9.597    Beijing         China     1357.00
4   1.221   Pretoria  South Africa       52.98
      area    capital       country  population
BR   8.516   Brasilia        Brazil      200.40
RU  17.100     Moscow        Russia      143.50
IN   3.286  New Dehli         India     1252.00
CH   9.597    Beijing         China     1357.00
SA   1.221   Pretoria  South Africa       52.98
          Date       Open       High        Low      Close  Adj Close  Volume
0   2017-08-18  23.830000  24.350000  23.670000  24.150000  24.150000   60900
1   2017-08-21  24.139999  24.160000  23.959999  24.110001  24.110001   43900
2   2017-08-22  24.360001  24.520000  23.959999  24.309999  24.309999   55800
3   2017-08-23  24.129999  24.510000  23.770000  24.280001  24.280001  126800
4   2017-08-24  24.410000  24.959999  24.219999  24.340000  24.340000  131300
5   2017-08-25  24.260000  24.799999  24.260000  24.389999  24.389999   99500
6   2017-08-28  24.420000  24.530001  24.080000  24.299999  24.299999   99500
7   2017-08-29  24.240000  24.520000  24.190001  24.270000  24.270000  108000
8   2017-08-30  24.270000  24.400000  23.910000  24.219999  24.219999  141200
9   2017-08-31  24.270000  24.540001  24.270000  24.490000  24.490000  223200
10  2017-09-01  24.510000  24.580000  24.290001  24.299999  24.299999   63300
11  2017-09-05  24.280001  24.500000  24.049999  24.209999  24.209999   94300
12  2017-09-06  24.209999  24.320000  23.900000  23.959999  23.959999   83700
13  2017-09-07  24.020000  24.059999  23.500000  23.570000  23.570000  177800
14  2017-09-08  23.549999  23.889999  23.150000  23.309999  23.309999  208800
15  2017-09-11  23.370001  23.670000  23.370001  23.500000  23.500000   99500
16  2017-09-12  23.450001  24.110001  23.450001  23.910000  23.910000   74100
17  2017-09-13  23.879999  24.270000  23.879999  24.150000  24.150000  125000
18  2017-09-14  24.129999  24.469999  23.780001  23.969999  23.969999  103100
19  2017-09-15  24.000000  24.190001  23.799999  23.920000  23.920000  316100
0     2017-08-18
1     2017-08-21
2     2017-08-22
3     2017-08-23
4     2017-08-24
5     2017-08-25
6     2017-08-28
7     2017-08-29
8     2017-08-30
9     2017-08-31
10    2017-09-01
11    2017-09-05
12    2017-09-06
13    2017-09-07
14    2017-09-08
15    2017-09-11
16    2017-09-12
17    2017-09-13
18    2017-09-14
19    2017-09-15
Name: Date, dtype: object
         Open
0   23.830000
1   24.139999
2   24.360001
3   24.129999
4   24.410000
5   24.260000
6   24.420000
7   24.240000
8   24.270000
9   24.270000
10  24.510000
11  24.280001
12  24.209999
13  24.020000
14  23.549999
15  23.370001
16  23.450001
17  23.879999
18  24.129999
19  24.000000
         Open      Close
0   23.830000  24.150000
1   24.139999  24.110001
2   24.360001  24.309999
3   24.129999  24.280001
4   24.410000  24.340000
5   24.260000  24.389999
6   24.420000  24.299999
7   24.240000  24.270000
8   24.270000  24.219999
9   24.270000  24.490000
10  24.510000  24.299999
11  24.280001  24.209999
12  24.209999  23.959999
13  24.020000  23.570000
14  23.549999  23.309999
15  23.370001  23.500000
16  23.450001  23.910000
17  23.879999  24.150000
18  24.129999  23.969999
19  24.000000  23.920000
         Date       Open   High        Low      Close  Adj Close  Volume
0  2017-08-18  23.830000  24.35  23.670000  24.150000  24.150000   60900
1  2017-08-21  24.139999  24.16  23.959999  24.110001  24.110001   43900
2  2017-08-22  24.360001  24.52  23.959999  24.309999  24.309999   55800
3  2017-08-23  24.129999  24.51  23.770000  24.280001  24.280001  126800
         Date   Open       High        Low      Close  Adj Close  Volume
4  2017-08-24  24.41  24.959999  24.219999  24.340000  24.340000  131300
5  2017-08-25  24.26  24.799999  24.260000  24.389999  24.389999   99500